export { default as Welcome } from './img_welcome.png';
export { default as Graph } from './graph.png';
export { default as OrderGraph } from './OrderGraph.png';
export { default as ProductGraph } from './ProductSold.png';
export { default as Engin } from './part1.png';
export { default as ClutchPlate } from './clutch_plate.png';
export { default as Earbox } from './earbox.png';
export { default as Tyre } from './Tyre.png';
export { default as Shock } from './shock.png';
