export { default as FileAvatar } from './ic_file_avatar.svg';
export { default as Email } from './ic_email.svg';
export { default as Password } from './password.svg';
export { default as Eye } from './ic_eye.svg';
export { default as Logo } from './ic_logo.svg';
export { default as EyeOff } from './ic_eye_off.svg';
export { default as RecaptchaLogo } from './recaptcha.png';
export { default as WhiteLogo } from './ic_white_logo.svg';
export { default as BackArrow } from './ic_arrow_back.svg';
